### Register
POST http://localhost:3000/auth/register
Content-Type: application/json

{"email": "test@test.de", "password": "geheim"}

###Login
POST http://localhost:3000/auth/login
Content-Type: application/json

{"email": "test@test.de", "password": "geheim"}